package caios.android.fanbox.core.logs.category

import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put

// This class is automatically generated by generate-log-classes.
sealed class NavigationLog : LogCategory {
    class Navigate internal constructor(
        private val screenRoute: String
    ) : NavigationLog() {
        override val properties: JsonObject = buildJsonObject {
            put("event_category", "navigation")
            put("event_name", "navigate")
            put("screen_route", screenRoute)
        }
    }

    companion object {
        // 画面遷移したときのログ
        fun navigate(
            screenRoute: String
        ) = Navigate(screenRoute)
    }
}
