package caios.android.fanbox.core.common.logs.category

import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put

// This class is automatically generated by generate-log-classes.
sealed class NavigationLog : LogCategory {
    class NavigateToScreen internal constructor(
        private val screenName: String,
        private val arguments: String?
    ) : NavigationLog() {
        override val properties: JsonObject = buildJsonObject {
            put("event_category", "navigation")
            put("event_name", "navigate_to_screen")
            put("screen_name", screenName)
            put("arguments", arguments)
        }
    }

    class NavigateToDialog internal constructor(
        private val dialogName: String,
        private val arguments: String?
    ) : NavigationLog() {
        override val properties: JsonObject = buildJsonObject {
            put("event_category", "navigation")
            put("event_name", "navigate_to_dialog")
            put("dialog_name", dialogName)
            put("arguments", arguments)
        }
    }

    companion object {
        // 画面遷移したときのログ
        fun navigateToScreen(
            screenName: String,
            arguments: String?
        ) = NavigateToScreen(screenName, arguments)

        // ダイアログを表示したときのログ
        fun navigateToDialog(
            dialogName: String,
            arguments: String?
        ) = NavigateToDialog(dialogName, arguments)
    }
}
